# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='Address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='Email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='Phone',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='City',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='State',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Zip',
            field=models.CharField(default='', max_length=200),
        ),
    ]
